project:
  type: website
  render:
    - index.qmd
    - cards/*.qmd
    - presentations/accuracy2trust/index.qmd
    - presentations/transformers4panel/index.qmd

website:
  page-navigation: true
  title: "2026 IAOS Conference - Vilnius - Meilame Tayebjee"
  site-url: https://meilame-tayebjee.github.io/IAOS-Vilnius-conference
  repo-url: https://github.com/meilame-tayebjee/IAOS-Vilnius-conference
  repo-branch: main
  navbar:
    right:
      - icon: github
        href: "https://github.com/meilame-tayebjee/IAOS-Vilnius-conference"
        aria-label: GitHub

execute:
  freeze: true
